spring:
  application:
    name: side  
  datasource:
    url: jdbc:mariadb://localhost:3306/side_project
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12348765
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update    